apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: cbk4tplsp-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/cbk4tplsp-dotnet-basic-gitops